use oyak; 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CLIENTS DIVERS","RUNGIS","C0"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("180","xxx","C0605"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("80","xxx","C0909"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("ESSAI EURO","RUNGIS","C1"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("AU GRAND BLEU MAUREPAS","VILLEPREUX","C10"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("JUILLET DANIEL","SARTROUVILLE","C100"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("SARL LES POISSONNERIES DE","PARIS","C101"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("EMOND MICHEL","GRETZ","C102"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("FINE DE FRANCE","PARIS","C1038"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("FISCH EXPRESS","BEI INSBRUCK AUTRICH","C104"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("L'OCEANIC","PARIS","C1049"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("BOSC VENTS ET MAREES","PARIS","C105"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CLUB DE LA MER","NAILLY","C1059"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("ELYES","MONTGERON","C106"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LEMAITRE","ORLEANS","C1061"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("EUROPA FISH","DUSSELDORF ALLEMAGNE","C1062"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LE CHALUT EURL","AUBIGNY SUR NERE","C107"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("PAOLO PECHE","BEZONS","C1070"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LA GRANDE CASCADE","PARIS","C1071"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("S.A. CELLERIER","ST MARTIN BELLEVUE","C1072"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CHRISFISH DANMARK A/S","FREDERIKSHAVN DK","C108"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("SAUFRAMER SARL","MONTLHERY","C109"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("SOPROMER S A R L","HAGONDANGE","C11"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("MAGMAE POIS.","AUNEUIL","C1105"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LE COMPTOIR","PARIS","C1107"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LA MASCOTTE","PARIS","C1108"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("HOSTACHY FRANCK","NOISEAU","C111"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("GOUBAULT","ARDENTES","C112"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("VIANDE DU TERROIR","RUNGIS","C113"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("S A S","RUNGIS","C1133"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("POIS. MAURICE","MERIEL","C114"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("GAYE","COURBEVOIE","C115"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("xxx","xxx","C1150"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LE MARLIN SARL","MARTRAGNY","C116"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CHAMPION MASSENA","PARIS","C117"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("PLEINE MER","DRANCY","C118"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("POIS. D'AUTEUIL","PARIS","C119"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("PALAIS DE LA MER","GOURNAY S/MARNE","C12"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("GARNIER ST LAZARE","PARIS","C120"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("NIGGEMANN","BOCHUM RFA","C121"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("GRANDE VAGUE (LA)","MANTES LA JOLIE","C122"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("GIOIA SARL","PARIS","C123"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("DROUET GERARD","EAUBONNE","C124"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("DRAVEIL MAREE","DRAVEIL","C125"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LOISEAU","NEVERS","C126"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CHARON SARL","BOULOGNE","C127"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CHAMPION DEMOURS","PARIS","C128"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LA BONNE MAREE","ST MAURICE S/FESSARD","C129"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("AUX PETITS BATEAUX SARL","SAULX MARCHAIX","C13"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("MATHERAT SARL","RUNGIS CEDEX","C130"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("DJELLEB GERARD","LYON 3{","C131"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("HAMON SARCELLES","SARCELLES","C132"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("INTER MAREE","HOUDAN","C133"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("AUBERGE DES AS","BRAINY","C134"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("SOCIETE IMBERT","VILLENEUVE LE ROI","C135"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("ETOILE DES MERS","PARIS","C136"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("BRASSERIE DES LILAS","PARIS","C137"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("STE SIMON","ST MAUR DES FOSSES","C138"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("JOYEUX CLAUDE","BONNEUIL S/MARNE","C139"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LE NECTAR DE LA MER","ST GERMAIN DE LA GRANG","C14"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CAFE BOUTARD","NEUILLY","C1400"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("BOUCHONS LES 15E","PARIS","C1402"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("ETANG DE BEAULIEU","STE GENEVIEVE DES BOIS","C142"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("SAUT DU POSTILLON","CORBEIL","C144"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("P V D","PARIS","C145"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LA PRIMAVERA","AUXERRE","C146"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("MEDITERANNEE HOLLANDE","ROTTERDAM HOLLAND","C147"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("G.-S. HAMON","ARGENTEUIL","C148"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("ATELIER BERGER","PARIS","C1481"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("TIR BOUCHON","PARIS","C1482"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("AU VENT DU LARGE","ST LEU LA FORET","C149"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LE VILLAGE","VILLEMONBLE","C15"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LELOY JEAN","POISSY","C150"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LA ROCHELLE ST AUGUSTIN","PARIS","C1500"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LEMARGUE","VITRY S/SEINE","C151"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("MITRECE GERARD","MEUDON LA FORET","C152"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("POIS DE FONTAINE","FONTAINE LES GRES","C153"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("PECHE COTIERE","CHERBOURG","C154"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("MIRANDA","MONTIGNY LES CORMEILLE","C155"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("M C S","RUNGIS","C156"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LANDOT","YERRES","C157"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LE LAGON","ST CYR DOURDAN","C158"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("DISTRIMER","CREPY EN VALOIS","C16"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("REGAL DE LA MER","MEHUN SUR YEVRE","C160"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("JARDIN GOURMAND DE","AUXERRE CEDEX","C1600"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("POINT DU JOUR","BLENAU","C1601"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LA TABLE DE WILLIAM FEVRE","CHABLIS","C1602"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LA POSTE","CHABLIS","C1603"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LA PETITE AUBERGE","VAUX","C1604"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("BLANCHE DE CASTILLE","BLENAU","C1605"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("FLOREVE SARL","AUXERRE","C1607"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LE RELAIS DE VILLEROY","VILLEROY","C1608"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("AUBERGE DE LA VANNE","SENS","C1609"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("PEPONE","PARIS","C161"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("PETIT CLARIDGE","THEMES CEZY","C1611"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LES CAPUCINS","AVALLON","C1612"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LA MADELEINE","SENS","C1614"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LA COTE ST JACQUES","JOIGNY CEDEX","C1615"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LYCEE VAUBAN","AUXERRE CEDEX","C1617"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("AU COCHON D'OR","SENS","C1618"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LEDREUX","PARIS","C162"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("L'ENFER DU GOUT","AUXERRE","C1621"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("HOSTELLERIE DES CLOS","CHABLIS","C1622"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LE COMMERCE","AUXERRE","C1623"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LA FEUILLETTE 132","CHABLIS","C1625"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LE BOUGAINVILLE","VEZELAY","C1627"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CHARCUTERIE SABRE","AUXERRE","C1628"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("L'OREE DES CHAMPS SARL","EPINEAU LES VOVES","C1629"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LE PETIT PORT","ST LEU LA FORET","C163"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("GELEE LIONEL","ST GEORGES S/BAULCHE","C1630"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("FESTINS DE BOURGOGNE","CHEMILLY S/YONNE","C1631"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LES FLEURS RESTAURANT","PONTAUBERT","C1632"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LA RIVE GAUCHE","JOIGNY","C1633"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LE SCHAEFFER","AUXERRE","C1634"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LA CHENEVOTTE","GUILLON","C1635"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("QUAI DE LA MARINE","AUXERRE","C1636"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("HOTEL DE VILLE","TOUCY","C1639"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("L'OCEANE POIS.","NANCY","C164"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CHATOYER SARL","AUXERRE","C1641"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("AUB. LE VOUTENAY","VOUTENAY S/CURE","C1642"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CRIEUR DE VIN","SENS","C1643"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("L'ANGELUS","CLAMECY","C1644"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("GRAND GOUSIER (AU)","AUXERRE","C1645"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("xxx","xxx","C1647"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("AUX PLAISIRS D'AILLEURS","AUXERRE","C1648"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("MESNAGE DANIEL","GIF S/ YVETTE","C165"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("MECHIN POISSONNERIE","MONTMORENCY","C166"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("MALVOLTI FRANCHI POIS.","BAILLET EN FRANCE","C167"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("MOREL NELLY","COURTENAY","C168"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("AUX POISSONS DE MER","BESANCON","C169"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("R D MAREES","BEAUMONT S/OISE","C17"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("MAREE VOLTAIRE","PARIS","C170"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("MOREAU GERARD","MONTLIGNON","C171"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("MECHET","MORANGIS","C172"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("GOESLIER SYLVAIN","MORSANG SUR ORGE","C174"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("MARIA","VITRY","C175"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("DERE","BEAULIEU S/LOIRE","C176"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("MICHELET ROL.7/3","LA GARENNE COLOMBES","C177"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("PECHERIE 18","PARIS","C18"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("PECHERIES DE ST MALO","SAINT MALO","C180"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("HUITRE SUR LE ZINC","RAMBOUILLET","C182"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("ETAPE GOURMANDE","VERSAILLES","C184"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("PECUNIA FRERES SARL","RUNGIS CEDEX","C186"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("DOMINIC","SOISY SUR ECOLE $","C187"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("POIS. DE LA GARE","CORMEILLES PARISIS","C188"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("BAUMGARTNER","COINCY","C189"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("SKIPPER","THIAIS","C19"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("NEPTUNE FISH","DUSSELDORF","C190"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("HARSANT.C","CORMEIL EN PARISIS","C191"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("SEVRES MAREE","SEVRES","C192"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("POIS. D'IVRY","OZOIR LA FERRIERE","C193"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("GOLDEN FISH (BELGIQUE)","BELGIQUE","C196"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("PARIS PECHE","PARIS","C197"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("POIS. BLEUE","PARIS","C198"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("SITARA","KREMLIN BICETRE","C199"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("GILLES","RUNGIS","C2"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("GUMBAU SARL","ENNERY","C20"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("MALAGA","CHEVILLY LARUE","C200"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("R S E SARL","JOINVILLE LE PONT","C201"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("POIS MARTINE ET PATRICK","CLAMART","C202"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("POIS. MODERNE BOURGEOIS","PARIS","C203"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("POIS. HENRI","LA COURNEUVE","C204"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("ROBERT POIS SARL","BOULOGNE","C205"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("POIS. DE L'OCEAN","SURESNES","C206"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("P.R.M.","RUNGIS CEDEX","C208"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("RENOU CHRISTINE","VILLEMOMBLE","C209"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("ETOILE DES MERS","ARPAJON","C21"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("POTTIER ET FILS","NANTERRE","C210"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("MAREE D'EQUINOXE","CHEVILLY LARUE","C211"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CHAVES","SAILLY","C212"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("950","xxx","C2120"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("DEQUEN THIERRY","CHATILLON","C213"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("BISTRO TATIN","BELGIQUE","C214"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("RENOU JEAN MICHEL","NEUILLY SUR MARNE","C215"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("ROYAL PECHE","BRETIGNY S/ORGE","C216"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("SAINT-PIERRE","PARIS","C217"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("BOUSCH S A R L","COLOMBES","C218"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("SOGUISA","PARIS","C219"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("L'AVENIR","PARIS","C22"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("ABRANTES","VILLEPARISIS","C220"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LE DUC","PARIS","C221"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LA GRANVILLAISE SAL","FAY AUX LOGES","C222"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("T'KINT","VERSAILLES","C223"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("TROIS S.I.","PARIS","C224"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("TARRY POIS.","GONESSE","C226"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("ZIAT","LA NORVILLE","C227"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("YELLOW SUBMARINE","LONGWY","C229"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("HYPPOCAMPE DISTRI IRENE","RUNGIS CEDEX","C23"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LA PIERRE DE CORAIL","MORET S/LOING","C230"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("VANHAMME PATRICK ET CHANT","VER/S/LAUNETTE","C232"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("ZYGOTHEQUE","PARIS","C233"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("DOMAINE DU RONCEMAY","CHASSY","C234"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("POIS. MARIA","VITRY SUR SEINE","C235"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("VISSE SARL","BOISSY ST LEGER","C236"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("POIS. ROY","LONGJUMEAU","C237"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("BRACKE FABRICE","BOURTH","C24"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LES PECHERS DU CAP","THIAIS","C240"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("ISTAMBUL FISH","KOLM.","C241"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("YOUSSEF SARL","DRANCY","C242"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("JFC RUNGIS SA.","RUNGIS CEDEX","C243"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("GOLF BLEU","SCY CHAZELLE","C244"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("SC DISTRIBUTION","rennes","C245"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("O.C.M SARL","MELUN","C246"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("HAMON CHAMPION","BOURG LA REINE","C248"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("THALASSA SCEAUX","SCEAUX","C249"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("BLUE MARLIN SARL","L'HAY LES ROSES","C25"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("PICHERY","PONT SUR YONNE","C250"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("PERREUX","CHEVILLY LARUE","C251"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("POIS DE LA FRESNAYE","NANTERRE","C252"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("BELLA VITA","ANGERVILLE","C253"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("TRANCHANT LILIANE","DAGNY","C254"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CERGY - MAREE","CERGY","C255"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("PECH. DE ST QUENTIN","BOUTIGNY PROUAIS","C256"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("RELAIS DES MERS","MANTES LA JOLIE","C258"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("COIGNARD","VITRY S/SEINE","C259"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("L'AGACHON","ST AUGUSTIN","C26"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("HAMON CHAMPION ST MARCEL","PARIS","C260"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("JOUGLEUX BERNARD","NEUVILLE AUX BOIS","C261"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LAFONT PHILIPPE","PARIS","C262"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LALANDE HERVE","SANNOIS","C264"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("ZANIN S A","VIRY CHATILLON","C266"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("BOUSCH BENJAMIN","FRANCONVILLE LA GARENN","C27"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("REMOND","RUNGIS","C270"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("JOUNIAUX ERIC","MAIGNELAY MONTIGNY","C272"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CITE DE LA MER","CORBEIL ESSONNES","C273"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("BILLAUT J.P.","LIVRY GARGAN","C275"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("REST OH DUO","PARIS","C276"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("ILE DE BREHAT","VERSAILLES","C278"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("BLANC S.A.","RUNGIS CEDEX","C28"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("DOYEN POISSONNERIE","VITRY S/SEINE","C280"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("BARNABET JEAN LUC","AUXERRE","C281"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("ISPC BREDA","NEDERLAND","C286"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LA MAREE DIMER SA","VERSAILLES","C287"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LA MAREE D'ARMOR SARL","COURBEVOIE","C288"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("MAGER","AUBERGENVILLE","C289"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("BONNEAU VINCENT","BOUSSY ST ANTOINE","C29"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("SARL POIS. DE L'ETOILE","BRISSON ST INNOCENT","C290"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LA FORCE DE L'OCEAN","ST MAUR","C291"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("RENAUDIN","VINCELOTTES","C292"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("ANAES MAREE","ST MAUR DES FOSSEES","C299"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("A L'ETOILE DE MER","HOUILLES","C3"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LA MAREE D'ARMOR","PARIS","C30"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("DELADOIRE","RUNGIS","C300"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("BRUNO MAREE 91","MONTLHERY","C303"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("J M B SARL","MONTFERMEIL","C31"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("BRELOY","SURESNES","C32"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("FISCHHAUS E","DUSSELDORF HEER","C330"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("xxx","xxx","C3333"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("950","xxx","C338."); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("BONNIVARD GILBERT","BRY SUR MARNE","C34"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("BRAZAO","CANNES","C35"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("VIDEO 8","CORBEIL","C350"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("DEBRIL","FRANCONVILLE GARENNE","C36"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("BEURY","NEUILLY EN THELLE","C360"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("BASSEZ ET CIE SARL","RUNGIS CEDEX","C361"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("REMY","MONTARGIS","C362"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("JOKA SARL","MEHUN S/YEVRE","C364"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("HUCHE ET CIE","PARIS","C365"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("BARRET SARL","BONDOUFLE","C366"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("POIS. LA BAUDROIE","CHAMPIGNY","C367"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("BAGOT POISSONNERIE","MONTEREAU","C368"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("J.P.F POIS SARL","JOINVILLE","C37"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("REFLETS 78 (SARL)","VILIERS ST FREDERIC","C370"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("JOLY PAUL","CHAMPAGNE S/SEINE","C373"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("SEBASTIEN SARL","GARCHES","C38"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("xxx","xxx","C382"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CORNIQUEL CHANTAL","CHAMPIGNY","C383"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CONTE MAURICE","CHAPONNAY","C384"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("ST JACQUES DIFFUSION SARL","SEVRAN","C387"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("AUX ECAILLES D'ARGENT","PARIS","C39"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CHAVIER","PARIS","C391"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("POIS DU CAP","VIRY CHATILLON","C392"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("RELAIS DE BEAUREGARD","BEAUREGARD","C393"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("PHARE DE NOISY","NOISY LE SEC","C394"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("ALAIN MARY","STE GENEVIEVE","C4"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("BOULOGNE S/MER-BEZARD","BOULOGNE BILLANCOURT","C40"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("DOF","JUVISY","C400"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("DANLOS","EVRY GREGY","C401"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("SOFREMI SARL","COLOMBES","C403"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("BAYEN","PARIS","C404"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("DEMAS","EPINAY","C405"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("POULIN PHILIPPE","CORMEILLES EN PARISI","C41"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LE ROCHELAIS","SOLERS","C42"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("FERME MARINE","TREMBLAY EN FRANCE","C420"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("FRAICHEUR MARINE","ST NOON LA BRETECHE","C421"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("ESPADON 3000","SOISSONS","C422"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("MARCHAND","RUNGIS","C43"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("BERNARD FRANCOIS","LA CHAPELLE ST PIERRE","C430"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("GACHOD","NANTEUIL LES MEAUX","C432"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("JACQUES ET JACQUELINE","PARIS","C436"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("BOUSCASSE CLAUDE","BOISSY ST LEGER","C44"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("VERRIERES MAREE","VERRIERES LE BUISSON","C45"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CROIX DE CHAVAUX","MONTREUIL","C450"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LA BOULONNAISE","PARIS","C451"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CHAMPION LECLERC","PARIS","C452"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("P.R.F","RUNGIS CEDEX","C455"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("HERRIER","PARIS","C457"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("GILLES ET CIE","RUNGIS CEDEX","C46"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CHEZ AUGUSTE","MONTEREAU","C47"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("NOUVELLES PECHERIES THIRY","ALFORVILLE","C470"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("JET MAREE","CHAMPIGNY S/MARNE","C472"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("J'OCEANE","RUNGIS CEDEX","C473"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("JACQUET GERARD","MAURECOURT","C474"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("MARINE DORNETS","SAVIGNY SUR CLAIRIS","C48"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LE SAUNIER","OLIVET","C480"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LEVILLY","PRINGY","C481"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("EUROPE FISH","GENTILLY","C482"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("GOURY YANNICK","MERIEL","C483"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("BOREL JEAN","DRANCY","C485"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LE CLUB DU POISSON SA.","NEUILLY","C487"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LES ABIES","MEHUN SUR YEVRE","C49"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("AUX PETITS PECHEURS","CORBEILLES EN GTS","C490"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("DITTIERE DOMINIQUE","BOULOGNE BILLANCOURT","C491"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("POIS. DE PASSY","PARIS","C495"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("MARTINE","RUNGIS","C5"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("BOUYER MAURICE","CLAMART","C50"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("NEAU LA MAREE","ST GERMAIN EN LAYE","C500"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("MOGLIA - LE CHALUT","MONTFERMEIL","C501"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("MAREE VENDEENNE","LE PLESSIS ROBINSON","C502"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("MAGHISSEN M.","VANVES","C503"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LANDIER CHRISTIAN","DOUY","C504"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("MAILLARD SERGE","SANNOIS","C505"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LA MAREE NORMANDE","COLOMBES","C506"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("MORIN J C","MONTREUIL","C508"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("POIS. MASSAT","LORRIS","C51"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("SINBAD","RUNGIS CEDEX","C510"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("SEPP SARL","PARIS","C52"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("REQUIN MARTEAU","MERIEL","C520"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("NEPTUNE MAREE","PERSAN","C521"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("MER ET OCEAN","CELY EN BIERRE","C522"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("AMOUROUX","RUNGIS","C53"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("NORMAND BOUTIQUE","PARIS","C530"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("FIDON NADINE","MARCILLY EN GAULT","C535"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("PECHE BRETONNE","RUNGIS","C536"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CLERGUE GEORGES","GLAIGNES","C54"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LECOURBE","PARIS","C540"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("POIS. JANICK","ANTONY","C541"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("POIS D'ONCY","ONCY","C542"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("MERS DU SUD","BOULOGNE BILLANCOURT","C543"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("POIS DU DOME","PARIS","C544"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("AUX FRUITS DE LA MER","LINAS","C55"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("TARAYRE & BERNIER","FRANCONVILLE","C550"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("COTE NORMANDE","PARIS","C56"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("VENTS ET MAREES","EPINAY SOUS SENART","C560"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("VIGNAS","NOISY LE SEC","C561"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LA MOUETTE","RENNES CEDEX","C563"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("PAVILLON BLEU","DRAVEIL","C566"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LA SALAMANDRE","AUXERRE","C567"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LE LION D'OR","VEZELAY","C568"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("GOELAND","VILLEJUIF","C569"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("POIS. SEBBAG","VILLEJUIF","C571"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("RUHLMAN","RUNGIS","C58"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LE GOUT DU LARGE","ARGENTEUIL","C580"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("POIS. PATRICK ET MARTINE","CLAMART","C581"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("POIS DU MIDI","VINCENNES","C583"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("POSEIDON","BRY SUR MARNE","C584"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("PLANTEC","ST MAUR","C586"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("PHM SARL","EVRY","C587"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("PAVILLON DES PRINCES","PARIS","C588"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CHEZ DIDIER (POIS.)","PONT ST MARIE","C59"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("TARAYRE L.","ERMONT","C591"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("BLEU CORAIL","BATILLY","C6"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("AUX FILETS BLEUS","FONTENAY S/BOIS","C60"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("PETITE PECHE BRETONNE (LA","PARIS","C600"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("POISSON D'OR","ALLEMAGNE","C601"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("BOS ERIC","DAMMARIE LES LYS","C602"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("124","xxx","C6060"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CHAPELLE SARL","RAMBOUILLET","C61"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("ESPADON","VERSAILLES","C62"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("POIS 2000","HERICY","C63"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CROISILLE JC.","MONTFERMEIL","C64"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("POIS. DE SENLIS","SENLIS","C640"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("BRASSERIE DE LA GARE","VILLENEUVE ST GEORGES","C641"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("COURBE CHANTAL","CHERONVILLIERS","C642"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CHAMPION MAUBEUGE","PARIS","C643"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("ROYAL FISCH","SOLINGEN ALLEMAGNE","C644"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CENTRE MAREE","NEVERS","C645"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CAP A L'OUEST","VOISINS LE BRETONNEUX","C646"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CAMUS FABRICE","CREPY EN VALOIS","C647"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CRUSTA POISSONS","PARIS","C648"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CENTRAL POISSONNERIE C","HAYANGE","C649"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("AU BORD DE LA MER","POISSY","C65"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("C.A.N.E.P.","ROMAINVILLE","C650"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("EXOCET","MONTARGIS","C651"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("GHILBERT SIMON J. CLAUDE","FONTENAY AUX ROSES","C652"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("J.P.B POISSONNERIES","NEUILLY SUR SEINE","C653"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CENTRALE POISSONNERIE L","LUXEMBOURG GARE","C654"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LA MAREE BRETONNE","THIONVILLE","C66"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LANNI - LE CHALUTIER","COMBS LA VILLE","C660"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("RM FRUITS SAS","PISCOP","C661"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("HIDEUX JEAN MARIE","MONTROUGE","C662"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("FIVABA","NOISY LE GRAND","C67"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CROZIER JEAN MICHEL","YERRES","C68"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LE GRAND CAFE","LUXEMBOURG","C69"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("MARINE ST GERMAIN","SAVIGNY S/CLAIRIS","C691"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("MAREE DISTRIBUTION","TORCY","C692"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("DANIEL JEAN MARIE","PALAISEAU","C693"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("ANTHONY MAREE","VITRY SUR SEINE","C7"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("MARTINE ET JEAN PIERRE","ALFORVILLE","C70"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("TOYER POISSONNERIE","MONTROUGE","C700"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("AIGUE MARINE","CROSNE","C701"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("BOILAY HOSTACHY","NOISEAU","C702"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("ROYAUME DES MERS","RUNGIS CEDEX","C703"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("REST. DE LA PAIX","PLEURS","C704"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CHAT PERCHE","DIMANCHEVILLE","C71"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("ILOT BLEU","DRAVEIL","C72"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("COUTARD G.","COLOMBES","C73"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("GALETS D'ETRETAT","PARIS","C739"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("FC MAREE","MONTFERMEIL","C74"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("SOFIMA","TOURLAVILLE","C740"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("AUX ZYGOMATES","PARIS","C741"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LE MOUSSAILLON","RUNGIS CEDEX","C742"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("MAREE DE BRETAGNE","PARIS","C744"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("OCEAN SERVICE","PONT SUR SEINE","C75"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("M S I","DRANCY","C76"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CABANE","BOBIGNY","C77"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("BRASSERIE GUILLAUME","LUXEMBOURG","C771"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("QUESNAY","ITTEVILLE","C772"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("VIGNAS SANDRINE","ANTONY","C773"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("UNION MAREE","RUNGIS CEDEX","C774"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CHATELET","ORLEANS","C78"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("MATHIAU DANIEL","MERIEL","C780"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LANGOUSTE (GAGNY)","GAGNY","C79"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("BESNARD S.A.","RUNGIS CEDEX","C790"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("RULHMAN","RUNGIS","C795"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CAPRICES DES MERS (AU)","LEVALLOIS PERRET","C8"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CARRE","SULLY S/LOIRE","C80"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("16","xxx","C80.1"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("ZIZZI","LUXEMBOURG","C801"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("TRONCHON LAURENT","YERRES","C802"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("VALLEE DE LA CERE","PALAISEAU","C81"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("BARRACUDA","L'HAY LES ROSES","C811"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("BIDARD JEAN PIERRE","LIMEIL BREVANNES","C82"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("FRANCE MER","LA VILLE DU BOIS","C820"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("FECAMP MAREE","FECAMP","C821"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("JUMIN SARL","BANNOST VILLEGAGNON","C831"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("GALLEN","CONCARNEAU","C832"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("DISTRIPECHE","BORAN SUR OISE","C84"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LORENZO JACKY","MAISONS ALFORT","C841"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("MARC L.","BRUYERES LE CHATEL","C842"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("RAVEL","BOURG LA REINE","C846"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("DEUX FRERES","GOUSSAINVILLE","C85"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("ILE DES PINS","MONTREUIL S/BOIS","C850"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LA PERROTINE","PARIS","C851"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LANGRIS","FERTE GAUCHER","C852"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("POIS DU VESINET","LE VESINET","C853"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("AUX POISSONS AVRIL SARL","AUXERRE","C854"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("S E P M","SURESNES","C855"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("S F P","WISSOUS","C856"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("GARNIER","MONTEREAU","C857"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LA LORRAINE","LUXEMBOURG","C858"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LE NORMAND TRAITEUR","FLEURY LES AUBRAIS","C859"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CAP BRETAGNE","WATERLOO BELGIQUE","C86"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LABEL-BLEU (REYNAUD)","RUNGIS CEDEX","C860"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("AU GRE DES FLOTS","ST DENIS","C861"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("DAGUERRE","PARIS","C862"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("ITALO MAREE","DOURDAN","C865"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("PARIS CAVIAR","PARIS","C866"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CRETEIL MAREE","CRETEIL","C867"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("SANHEIRO","VILLIERS S/MARNE","C868"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("AUBERGE DU VAL DE BIEVRES","BIEVRES","C869"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("POIS DE LA COURONNE SARL","PITHIVIERS","C87"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("L'A B C DE LA MER","NEUILLY PLAISANCE","C870"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LA MEDITERRANEE","1070 BRUXELLES","C871"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("M. ET S. (POISSONNERIE)","CHOISY LE ROI","C872"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("L'ODYSEE MARINE","NOGENT SUR MARNE","C873"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CHABIN DANIEL","AUXERRE","C875"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CHABIN MICHEL","AUXERRE","C876"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("DORE DIDIER","COULOMMIERS","C878"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LE RELAIS FLEURI","AVALLON CEDEX","C879"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CUVILLIER","LAGNY S/MARNE","C88"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("PECH. DU VAL D'YERRES","QUINCY SOUS SENART","C880"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LA TAVERNE DE","AUXERRE","C881"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LA TERRASSE","PARIS","C882"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LA BELLE PALANGRE","BRAY SUR SEINE","C883"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LE POT D'ETAIN","ISLE S/SEREIN","C884"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LAETIMO POIS.","CORMEILLE EN PARISIS","C885"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LECONTE JEAN PIERRE","STE GENEVIEVE DES BOIS","C886"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("L'ORQUE","PARIS","C887"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LA BONNE PECHE 93","LE BLANC MESNIL","C888"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CHAPRAIS NOUVELLE VAGUE","BESANCON","C889"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("DELTA FISH","LA FLECHE CEDEX","C89"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("DECOURTY DANIEL","CORBEIL-ESSONNES","C890"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("MAREE 17","PARIS","C891"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("MENAU","S/PERE S/VEZELAY","C892"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("ROCHON ANDRE","MONETEAU","C893"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("L'HUITRIERE","VERSAILLES","C894"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CHAMCIPER","RUNGIS CEDEX","C895"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("PARIS R.G","RUNGIS CEDEX","C896"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("DORE POISSONNERIE","MONTFERMEIL","C897"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LES NEREIDES","LAGNY S/MARNE","C898"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("ANTARTICA STE","PARIS","C899"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CARIO ALAIN","VARENNES VAUZELLES","C9"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("DELPECH MICHEL","PROVINS","C90"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CLIENTS DIVERS ETRANGER","xxx","C901"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("MAROC SHOP","BONN ALLEMAGNE","C902"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LES DEUX FRERES","FONTENAY LE VICOMTE","C903"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("PECHERIE DES LILAS","RUNGIS CEDEX","C904"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("POIS. LE NAUTILUS","MEUDON LA FORET","C905"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CASADO OLIVIER","HOUILLES","C906"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("BARDET","GENNEVILLIERS","C907"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("GRAND ARGENTIER","BOURGES","C908"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("POIS. POINT DU JOUR","BOULOGNE","C909"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("JAMOIS ROGER PASCAL","DUEIL LA BARRE","C910"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("SAINT FURCY","LAGNY","C912"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("L'ATLANTIQUE","ARGENTEUIL","C913"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("AU DAUPHIN JOINVILLOIS","DAILLANCOURT","C914"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("HOSTELLERIE DE LA POSTE","AVALLON","C915"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CHAMPION BARBES","PARIS","C916"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("PEREIRA MOREIRA","ASNIERES S/OISE","C917"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LANGLOIS","ST ETIENNE AU MONT","C918"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("FLAMBEAUX","ORMOY","C919"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CARDAMOME","IVRY SUR SEINE","C92"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("TRI MATELOT","LE KREMLIN BICETRE","C920"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("SARL PECHERIES BOULONNAIS","REIMS","C921"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("HUGUET A.","BRETIGNY SUR ORGE","C922"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("BLUE FISCH","VILLEMUR S/TARN","C923"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("YVONNET","LA GENEVRAYE","C924"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("COTE SAUVAGE","BEAUNE","C925"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CHASSE MAREE","PARIS","C927"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("REST. LE MAXIME","AUXERRE","C928"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("ABYSS","L'HAY LES ROSES","C929"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("DELARGILLIERE","PARIS","C93"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("SMB BRAZAO SARL","PARIS","C930"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("AU POISSON DORE","PARIS","C931"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("xxx","xxx","C932"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("GOLDEN FISH","BAGNOLET","C933"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("RAYE JP","MONTMAGNY","C934"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("AU POISSON VOLANT","ORLY","C935"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("REYNAUD","RUNGIS CEDEX","C936"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("OCEANIC PALAISEAU SARL","PALAISEAU","C937"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CALANQUES (LES)","TREMBLAY EN FRANCE","C938"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("DAUPHIN DU FAUBOURG","PARIS","C939"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("HOUILLE DIDIER","DRANCY","C94"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("URY","PARIS","C940"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("DELAITRE PATRICK","COINCY","C941"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("LEVASSEUR","LE CROTOIS","C942"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CHAMPION ST MARCEL","PARIS","C943"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("SUPER FISH","BRUXELLES","C945"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CERQUERA","MONTIGNY LES BRET.","C946"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("POIS DU PONT","GIEN","C947"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("POIS.AUBERT JEROME","L'AIGLE","C948"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("ARGO FISHEREI","KORNWESTHEIM","C949"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("DEMARNE FRERES","RUNGIS M I N","C95"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("POIS DU MIROIR","MELUN","C950"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("AUMACA STE","FALAISE","C951"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("BILLEN S.A.","RUNGIS M I N","C952"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("DACQUET","RUNGIS CEDEX","C953"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("PITZ MOREIRA","LE MESNIL AUBRY","C954"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("DIF' OCEAN","MONTIGNY LES BRETONNEU","C955"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("xxx","xxx","C956"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("AU ROCHER DE CANCALE","METZ","C957"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("MAILLET NADIA","ERMONT","C958"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("MAXI PESCA","BRUXELLES","C959"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("PEAN","RUNGIS","C96"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("RICHARD V.","GOMETZ LE CHATEL","C960"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("ROCHES ROUGES","DRANCY","C961"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CHAMPION PUISEUX","PUISEUX","C962"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("ETELLOISE POIS.","PARIS","C97"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("AU GRAND BLEU","PARIS","C98"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("MAREE GOURMANDE","MONTFERMEIL","C99"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("MANDATAIRES DIVERS","RUNGIS CEDEX","C998"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("CLIENTS DIVERS","RUNGIS","C999"); 
INSERT into pcfact_clients (societe,ville,clef) VALUES("
"); 
